"""API and domain schema package."""

from app.schemas.audit import (
    ArtifactKind,
    AuditEvent,
    AuditEventType,
    AuditMetadata,
    AuditMetadataValue,
    CaseArtifactPath,
    SummaryAuditDecisionStatus,
    SummaryAuditFactReference,
    SummaryAuditRecoveryState,
    SummaryAuditSourceReference,
    SummaryAuditTrace,
    SummaryAuditTraceMetadata,
)
from app.schemas.auth import (
    AuthorizationError,
    CallerContext,
    CallerRole,
    Capability,
)
from app.schemas.case import (
    CaseCoreRecords,
    CaseRecordKind,
    CaseRecordReference,
    CaseStatus,
    CaseTransition,
    CaseTransitionError,
    PatientCase,
    generate_case_id,
)
from app.schemas.consent import ConsentCaptureResult, ConsentOutcome
from app.schemas.document import (
    DocumentUploadMessageKind,
    DocumentUploadMetadata,
    DocumentUploadResult,
)
from app.schemas.extraction import (
    CaseExtractionRecord,
    DocumentProcessingResult,
    OCRTextExtractionResult,
)
from app.schemas.handoff import (
    DoctorCaseCard,
    DoctorCaseCardDelivery,
    DoctorCaseCardRejection,
    DoctorReadyCaseNotification,
    DoctorReadyCaseNotificationDelivery,
    DoctorReadyCaseNotificationRejection,
    DoctorReadyCaseNotificationStatus,
)
from app.schemas.indicator import (
    CaseIndicatorExtractionRecord,
    StructuredIndicatorValue,
    StructuredMedicalIndicator,
)
from app.schemas.knowledge_base import (
    KnowledgeApplicability,
    KnowledgeBaseCollectionConfig,
    KnowledgeProvenance,
    KnowledgeSeedEntry,
    KnowledgeSourceMetadata,
)
from app.schemas.patient import (
    ConsultationGoal,
    ConsultationGoalCaptureResult,
    PatientIntakeCaptureResult,
    PatientIntakeField,
    PatientIntakeMessageKind,
    PatientIntakePayload,
    PatientIntakeUpdateResult,
    PatientProfile,
)
from app.schemas.rag import (
    CitationReference,
    DoctorFacingDeviationMarker,
    DoctorFacingQuestion,
    DoctorFacingSummaryDraft,
    DoctorFacingUncertaintyMarker,
    GeneratedNarrativeClaim,
    GroundedFact,
    GroundedSummaryContract,
    KnowledgeApplicabilityDecision,
    KnowledgeRetrievalMatch,
    KnowledgeRetrievalResult,
    RetrievalIndicatorContext,
    SummaryValidationResult,
)
from app.schemas.safety import SafetyCheckResult, SafetyIssue

__all__ = [
    "AuthorizationError",
    "CallerContext",
    "CallerRole",
    "Capability",
    "AuditEvent",
    "AuditEventType",
    "AuditMetadata",
    "AuditMetadataValue",
    "ArtifactKind",
    "CaseArtifactPath",
    "SummaryAuditDecisionStatus",
    "SummaryAuditFactReference",
    "SummaryAuditRecoveryState",
    "SummaryAuditSourceReference",
    "SummaryAuditTrace",
    "SummaryAuditTraceMetadata",
    "CaseCoreRecords",
    "CaseRecordKind",
    "CaseRecordReference",
    "CaseStatus",
    "CaseTransition",
    "CaseTransitionError",
    "ConsentCaptureResult",
    "ConsentOutcome",
    "ConsultationGoal",
    "ConsultationGoalCaptureResult",
    "DocumentUploadMessageKind",
    "DocumentUploadMetadata",
    "DocumentUploadResult",
    "CaseExtractionRecord",
    "CaseIndicatorExtractionRecord",
    "DocumentProcessingResult",
    "KnowledgeApplicability",
    "KnowledgeBaseCollectionConfig",
    "KnowledgeProvenance",
    "KnowledgeSeedEntry",
    "KnowledgeSourceMetadata",
    "KnowledgeApplicabilityDecision",
    "KnowledgeRetrievalMatch",
    "KnowledgeRetrievalResult",
    "DoctorFacingDeviationMarker",
    "DoctorFacingQuestion",
    "DoctorFacingSummaryDraft",
    "DoctorFacingUncertaintyMarker",
    "DoctorReadyCaseNotification",
    "DoctorReadyCaseNotificationDelivery",
    "DoctorReadyCaseNotificationRejection",
    "DoctorReadyCaseNotificationStatus",
    "DoctorCaseCard",
    "DoctorCaseCardDelivery",
    "DoctorCaseCardRejection",
    "CitationReference",
    "GeneratedNarrativeClaim",
    "GroundedFact",
    "GroundedSummaryContract",
    "OCRTextExtractionResult",
    "PatientIntakeCaptureResult",
    "PatientIntakeField",
    "PatientIntakeMessageKind",
    "PatientIntakePayload",
    "PatientIntakeUpdateResult",
    "PatientProfile",
    "PatientCase",
    "StructuredMedicalIndicator",
    "RetrievalIndicatorContext",
    "SummaryValidationResult",
    "SafetyCheckResult",
    "SafetyIssue",
    "StructuredIndicatorValue",
    "generate_case_id",
]
